OnlineTicket/Controllers/HomeController.cs
using Bll;
using Common.Cache;
using IBll;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineTicket.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            //从缓存里面拿到userLoginId信息
            string userLoginId = HttpContext.Request.Cookies["userLoginId"].Value.ToString();
            UserInfo userInfo = CacheHelper.GetCache(userLoginId) as UserInfo;
            return View(userInfo);
        }


        /// <summary>
        /// 图表一，展示每日售票数量
        /// </summary>
        /// <returns></returns>
        public ActionResult Chartone()
        {
            return View();
        }


        /// <summary>
        /// 图表二，展示每日收入统计
        /// </summary>
        /// <returns></returns>
        public ActionResult Charttwo()
        {
            return View();
        }

        /// <summary>
        /// 欢迎界面
        /// </summary>
        /// <returns></returns>
        public ActionResult Welcome()
        {
            return View();
        }
    }
}

OnlineTicket/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using Common.Md5;
using IBll;
using Bll;
using OnlineTicket.Models;
using Common.VCode;
using Common.Cache;
using Model.Enum;
using Model.other;
using System.Linq.Expressions;

namespace OnlineTicket.Controllers
{
    public class UserInfoController : Controller
    {

        private IUserInfoService userinfoService = new UserInfoService();

        [LoginCheckFilterAttribute(IsCheck = false)]
        public ActionResult Login()
        {
            return View();
        }

        [LoginCheckFilterAttribute(IsCheck = false)]
        public ActionResult ShowVCode()
        {
            VCodeHelper validateCode = new VCodeHelper();
            string strCode = validateCode.RandomCode(4);

            //把验证码放到session中
            Session["VCode"] = strCode;

            byte[] imgBytes = validateCode.CreatVCodeImgs(strCode);

            return File(imgBytes, "image/jpeg");
        }

        /// <summary>
        /// 登陆信息验证
        /// </summary>
        /// <returns></returns>
        [LoginCheckFilterAttribute(IsCheck = false)]
        public ActionResult ProcessLogin()
        {
            //1 处理验证码

            string strCode = Request["vcode"];
            //拿到session中的验证码做对比
            string sessionCode = Session["VCode"] as string;

            //取过验证码，马上置空
            Session["VCode"] = null;

            //在测试阶段可以注释这段，就不需要填写验证码了
            //if (string.IsNullOrEmpty(sessionCode) || strCode != sessionCode)
            //{
            //    // "alert('ok！');", "text/javascript"
            //    return Json("验证码错误！");
            //}


            //2 处理用户名和密码
            string login = Request["login"];
            string pwd = Request["pwd"].GetMd5();

            var userinfo = userinfoService.GetEntities(u => u.Login == login && u.Pwd == pwd && u.Type == (int)UiTypeEnum.Admin).FirstOrDefault();

            if (userinfo == null)
            {
                return Json("用户名或密码错误!");
            }

            //登录成功，把用户信息放到Cache里,记录登陆时间
            userinfo.LoginDate = DateTime.Now;
            userinfoService.Update(userinfo);
            //1,立即分配一个标志，guid，作为key存入mm，同时把这个key存入客户端cookie
            string userLoginId = Guid.NewGuid().ToString();

            //把用户数据写入缓存
            CacheHelper.AddCache(userLoginId, userinfo, DateTime.Now.AddMinutes(20));

            //往客户端写入cookie
            Response.Cookies["userLoginId"].Value = userLoginId;


            //正确跳转到首页
            //return RedirectToAction("Test","Index");

            return Json("ok");

        }

        /// <summary>
        /// 登陆成功后，获取跳转的页面
        /// </summary>
        /// <returns></returns>
        public ActionResult ActionUrl()
        {
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// 退出登陆请求
        /// </summary>
        /// <returns></returns>
        public ActionResult ExitLogin()
        {
            string userloginid = Request.Cookies["userLoginId"].Value.ToString();
            //登陆信息置空
            if (!string.IsNullOrWhiteSpace(userloginid))
            {
                CacheHelper.RemCache(userloginid);
            }

            return RedirectToAction("Login");
        }





        /// <summary>
        /// 已通过核验的旅客账户管理显示页面
        /// </summary>
        /// <returns></returns>
        public ActionResult GuestIndex()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GuestIndex(PagingInfo pi, UserInfo ui)
        {
            pi.PageIndex = pi.PageIndex == 0 ? 1 : pi.PageIndex;
            pi.PageSize = pi.PageSize == 0 ? 5 : pi.PageSize;

            ui.IdCard = String.IsNullOrWhiteSpace(ui.IdCard) ? "" : ui.IdCard;
            ui.UName = String.IsNullOrWhiteSpace(ui.UName) ? "" : ui.UName;
            ui.Login = String.IsNullOrWhiteSpace(ui.Login) ? "" : ui.Login;

            Expression<Func<UserInfo, bool>> wherelambda = u => (u.Type == (int)UiTypeEnum.Guest && u.Status == (int)UiStatusEnum.Pass && u.IdCard != null && u.UName != null && u.Login != null && u.IdCard.Contains(ui.IdCard) && u.UName.Contains(ui.UName) && u.Login.Contains(ui.Login));

            int count = 0;
            var guestlist = userinfoService.GetPageEntities<int>(pi.PageSize, pi.PageIndex, out count, wherelambda, u => u.ID, true) as IEnumerable<UserInfo>;
            pi.TotalItems = count;

            return Json(Tuple.Create(guestlist, pi));
        }


        /// <summary>
        /// 没有通过核验的旅客账户管理显示页面,等待检验
        /// </summary>
        /// <returns></returns>
        public ActionResult GuestAwaitIndex()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GuestAwaitIndex(PagingInfo pi, UserInfo ui)
        {
            pi.PageIndex = pi.PageIndex == 0 ? 1 : pi.PageIndex;
            pi.PageSize = pi.PageSize == 0 ? 5 : pi.PageSize;

            ui.IdCard = String.IsNullOrWhiteSpace(ui.IdCard) ? "" : ui.IdCard;
            ui.UName = String.IsNullOrWhiteSpace(ui.UName) ? "" : ui.UName;
            ui.Login = String.IsNullOrWhiteSpace(ui.Login) ? "" : ui.Login;

            Expression<Func<UserInfo, bool>> wherelambda = u => (u.Type == (int)UiTypeEnum.Guest && u.Status == (int)UiStatusEnum.Block && u.IdCard != null && u.UName != null && u.Login != null && u.IdCard.Contains(ui.IdCard) && u.UName.Contains(ui.UName) && u.Login.Contains(ui.Login));

            int count = 0;
            var guestlist = userinfoService.GetPageEntities<int>(pi.PageSize, pi.PageIndex, out count, wherelambda, u => u.ID, true) as IEnumerable<UserInfo>;
            pi.TotalItems = count;

            return Json(Tuple.Create(guestlist, pi));
        }

        /// <summary>
        /// 展示乘客详情，注意将一些私密信息加密
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GuestDetails(int id = 0)
        {
            UserInfo userinfo = userinfoService.GetEntities(u => u.ID == id).First() as UserInfo;
            if (userinfo == null)
            {
                return HttpNotFound();
            }
            if (userinfo.IdCard.Length >= 16)
            {
                userinfo.IdCard = userinfo.IdCard.Substring(0, 8) + "*******" + userinfo.IdCard.Substring(12, 3);
            }

            return View(userinfo);
        }



        /// <summary>
        /// 修改密码界面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditPwd(int id = 0)
        {
            UserInfo userinfo = userinfoService.GetEntities(u => u.ID == id).First() as UserInfo;
            if (userinfo == null)
            {
                return HttpNotFound();
            }
            return View(userinfo);
        }


        [HttpPost]
        public ActionResult EditPwd(UserInfo userinfo)
        {
            if (userinfoService.EditPwd(userinfo.ID, userinfo.Pwd))
            {
                return Json("ok");
            }
            return View(userinfo);
        }

        /// <summary>
        /// 校验通过申请
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GuestPass(int id = 0)
        {
            if (userinfoService.GuestPass(id))
            {
                return Json("ok");
            }
            return HttpNotFound();
        }


        [HttpPost]
        public ActionResult UserInfoDelete(int id = 0)
        {
            UserInfo userinfo = userinfoService.GetEntities(u => u.ID == id).FirstOrDefault();
            if (userinfo == null)
            {
                return HttpNotFound();
            }
            if (userinfoService.Delete(userinfo))
            {
                return Json("ok");
            }
            return Json("ok");
        }




        /// <summary>
        /// 窗口账户
        /// </summary>
        /// <returns></returns>
        public ActionResult AdminIndex()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdminIndex(PagingInfo pi, UserInfo ui)
        {
            pi.PageIndex = pi.PageIndex == 0 ? 1 : pi.PageIndex;
            pi.PageSize = pi.PageSize == 0 ? 5 : pi.PageSize;

            ui.IdCard = String.IsNullOrWhiteSpace(ui.IdCard) ? "" : ui.IdCard;
            ui.UName = String.IsNullOrWhiteSpace(ui.UName) ? "" : ui.UName;
            ui.Login = String.IsNullOrWhiteSpace(ui.Login) ? "" : ui.Login;

            Expression<Func<UserInfo, bool>> wherelambda = u => (u.Type == (int)UiTypeEnum.Admin && u.IdCard != null && u.UName != null && u.Login != null && u.IdCard.Contains(ui.IdCard) && u.UName.Contains(ui.UName) && u.Login.Contains(ui.Login));

            int count = 0;
            var adminlist = userinfoService.GetPageEntities<int>(pi.PageSize, pi.PageIndex, out count, wherelambda, u => u.ID, true) as IEnumerable<UserInfo>;
            pi.TotalItems = count;

            return Json(Tuple.Create(adminlist, pi));
        }



        /// <summary>
        /// 添加管理员账户
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateAdmin()
        {
            return View();
        }

        /// <summary>
        /// 添加管理员账户
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateAdmin(UserInfo ui)
        {
            if (!userinfoService.LoginExist(ui.Login))
            {
                ui.SignDate = DateTime.Now;
                ui.Pwd = "123456".GetMd5();
                ui.Type = (int)UiTypeEnum.Admin;
                ui.Status = (int)UiStatusEnum.Pass;
                ui.GUID = Guid.NewGuid().ToString();
                if (userinfoService.Add(ui))
                {
                    return Json("ok");
                }
            }

OnlineTicket/Views/Home/Chartone.cshtml
@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" type="text/css" href="~/Content/static/h-ui/css/H-ui.min.css" />
<link rel="stylesheet" type="text/css" href="~/Content/static/h-ui.admin/css/H-ui.admin.css" />
<link rel="stylesheet" type="text/css" href="~/Content/lib/Hui-iconfont/1.0.8/iconfont.css" />
<link rel="stylesheet" type="text/css" href="~/Content/static/h-ui.admin/skin/default/skin.css" id="skin" />
<link rel="stylesheet" type="text/css" href="~/Content/static/h-ui.admin/css/style.css" />
<!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
<title>折线图</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 图表统计 <span class="c-gray en">&gt;</span> 每日售票统计 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="page-container">
	<div class="f-14 c-error">提示：该页面属于暂时为模拟数据</div>
	<div id="container" style="min-width:700px;height:400px"></div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="~/Content/lib/jquery/1.9.1/jquery.min.js"></script> 
<script type="text/javascript" src="~/Content/lib/layer/2.4/layer.js"></script>
<script type="text/javascript" src="~/Content/static/h-ui/js/H-ui.min.js"></script> 
<script type="text/javascript" src="~/Content/static/h-ui.admin/js/H-ui.admin.js"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="~/Content/lib/hcharts/Highcharts/5.0.6/js/highcharts.js"></script>
<script type="text/javascript" src="~/Content/lib/hcharts/Highcharts/5.0.6/js/modules/exporting.js"></script>
<script type="text/javascript">
    $(function () {
        Highcharts.chart('container', {
            title: {
                text: '近12天售票数量折线图',
                x: -20 //center
            },
            subtitle: {
                text: '在线售票数量和窗口售票数量',
                x: -20
            },
            xAxis: {
                categories: ['一', '二', '三', '四', '五', '六', '七', '八', '九', '十', '十一', '十二']
            },
            yAxis: {
                title: {
                    text: '车票数量'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: '张'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: '在线售票数',
                data: [10, 11, 14, 16, 17, 25, 30, 31, 29, 25, 19, 13]
            }, {
                name: '窗口售票数',
                data: [9, 10, 16, 15, 19, 26, 35, 34, 31, 30, 20, 19]
            }, {
                name: '退票数量',
                data: [2, 3, 2, 4, 5, 6, 7, 2, 1, 2, 1, 3]
            }]
        });
    });
</script>
</body>
</html>

OnlineTicket/Views/Home/Index.cshtml
@model Model.UserInfo

@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<link rel="Bookmark" href="/favicon.ico" >
<link rel="Shortcut Icon" href="/favicon.ico" />
<!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>
<![endif]-->

<link rel="stylesheet" type="text/css" href="~/Content/static/h-ui/css/H-ui.min.css" />
<link rel="stylesheet" type="text/css" href="~/Content/static/h-ui.admin/css/H-ui.admin.css" />
<link rel="stylesheet" type="text/css" href="~/Content/lib/Hui-iconfont/1.0.8/iconfont.css" />
<link rel="stylesheet" type="text/css" href="~/Content/static/h-ui.admin/skin/default/skin.css" id="skin" />
<link rel="stylesheet" type="text/css" href="~/Content/static/h-ui.admin/css/style.css" />
<!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
<title>在线汽车订票系统</title>
</head>
<body>
<header class="navbar-wrapper">
	<div class="navbar navbar-fixed-top">
		<div class="container-fluid cl"> <a class="logo navbar-logo f-l mr-10 hidden-xs" href="/aboutHui.shtml">汽车票预定系统</a> <a class="logo navbar-logo-m f-l mr-10 visible-xs" href="/aboutHui.shtml">车站管理员</a> 
			<span class="logo navbar-slogan f-l mr-10 hidden-xs">v1.0</span> 
			<a aria-hidden="false" class="nav-toggle Hui-iconfont visible-xs" href="javascript:;">&#xe667;</a>
			<nav class="nav navbar-nav">
				
		</nav>
		<nav id="Hui-userbar" class="nav navbar-nav navbar-userbar hidden-xs">
			<ul class="cl">
				<li>@Model.UName</li>
				<li class="dropDown dropDown_hover">
					<a href="#" class="dropDown_A">@Model.Login<i class="Hui-iconfont">&#xe6d5;</i></a>
					<ul class="dropDown-menu menu radius box-shadow">
						<li>@Html.ActionLink("退出登陆", "ExitLogin", "UserInfo")</li>

				</ul>
			</li>
				
				<li id="Hui-skin" class="dropDown right dropDown_hover"> <a href="javascript:;" class="dropDown_A" title="换肤"><i class="Hui-iconfont" style="font-size:18px">&#xe62a;</i></a>
					<ul class="dropDown-menu menu radius box-shadow">
						<li><a href="javascript:;" data-val="default" title="默认（黑色）">默认（黑色）</a></li>
						<li><a href="javascript:;" data-val="blue" title="蓝色">蓝色</a></li>
						<li><a href="javascript:;" data-val="green" title="绿色">绿色</a></li>
						<li><a href="javascript:;" data-val="red" title="红色">红色</a></li>
						<li><a href="javascript:;" data-val="yellow" title="黄色">黄色</a></li>
						<li><a href="javascript:;" data-val="orange" title="橙色">橙色</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</div>
</div>
</header>
<aside class="Hui-aside">
	<div class="menu_dropdown bk_2">
		<dl id="menu-article">
			<dt><i class="Hui-iconfont">&#xe6d0;</i> 窗口服务<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="/Ticketinfo/ShowTicket" data-title="售票系统" href="javascript:void(0)">售票系统</a></li>
                    <li><a data-href="/Ticketinfo/DoneIndex" data-title="退票系统" href="javascript:void(0)">退票系统</a></li>
                    <li><a data-href="/Ticketinfo/HistroyTicket" data-title="历史车票" href="javascript:void(0)">历史车票</a></li>
			</ul>
		</dd>
	</dl>

        @*<dl id="menu-comments">
			<dt><i class="Hui-iconfont">&#xe622;</i> 预约车票<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="feedback-list.html" data-title="预约信息" href="javascript:;">预约信息</a></li>
					<li><a data-href="feedback-list.html" data-title="已售预约" href="javascript:void(0)">已售预约</a></li>
                    <li><a data-href="feedback-list.html" data-title="过期预约" href="javascript:void(0)">过期预约</a></li>
			</ul>
		</dd>*@
	</dl>

        <dl id="menu-picture">
			<dt><i class="Hui-iconfont">&#xe61e;</i> 图表统计<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="/Home/Chartone" data-title="售票统计" href="javascript:void(0)">每日售票统计</a></li>
                    <li><a data-href="/Home/Charttwo" data-title="收入统计" href="javascript:void(0)">每日收入统计</a></li>
			</ul>
		</dd>
	</dl>

        <dl id="menu-tongji">
			<dt><i class="Hui-iconfont">&#xe61a;</i> 路线管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="/PathInfo/Index" data-title="路线信息" href="javascript:void(0)">路线信息</a></li>
			</ul>
		</dd>
	</dl>

        <dl id="menu-system">
			<dt><i class="Hui-iconfont">&#xe669;</i> 班车管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="/FlightInfo/Index" data-title="每日班车" href="javascript:void(0)">每日班车</a></li>
					<li><a data-href="/FlightInfo/TempFlightIndex" data-title="临时加班车" href="javascript:void(0)">临时加班车</a></li>
                    <li><a data-href="/FlightInfo/HistoryFlightIndex" data-title="历史加班车" href="javascript:void(0)">历史加班车</a></li>
			</ul>
		</dd>
	</dl>

        <dl id="menu-member">
			<dt><i class="Hui-iconfont">&#xe60d;</i> 旅客账户<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="/UserInfo/GuestAwaitIndex" data-title="账号核验" href="javascript:;">账号核验</a></li>
					<li><a data-href="/UserInfo/GuestIndex" data-title="账号管理" href="javascript:;">账号管理</a></li>
			</ul>
		</dd>
	</dl>


        <dl id="menu-admin">
			<dt><i class="Hui-iconfont">&#xe62d;</i> 工作账户<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="/UserInfo/AdminIndex" data-title="窗口账户" href="javascript:void(0)">窗口账户</a></li>
					<li><a data-href="/UserInfo/TellerIndex" data-title="检票账户" href="javascript:void(0)">检票账户</a></li>
			</ul>
		</dd>
	</dl>

		
		@*<dl id="menu-product">
			<dt><i class="Hui-iconfont">&#xe620;</i> 产品管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="product-brand.html" data-title="品牌管理" href="javascript:void(0)">品牌管理</a></li>
					<li><a data-href="product-category.html" data-title="分类管理" href="javascript:void(0)">分类管理</a></li>
					<li><a data-href="product-list.html" data-title="产品管理" href="javascript:void(0)">产品管理</a></li>
			</ul>
		</dd>
	</dl>*@
		
		
		
		
		
</div>
</aside>
<div class="dislpayArrow hidden-xs"><a class="pngfix" href="javascript:void(0);" onClick="displaynavbar(this)"></a></div>
<section class="Hui-article-box">
	<div id="Hui-tabNav" class="Hui-tabNav hidden-xs">
		<div class="Hui-tabNav-wp">
			<ul id="min_title_list" class="acrossTab cl">
				<li class="active">
					<span title="我的桌面" data-href="Welcome">我的桌面</span>
					<em></em></li>
		</ul>
	</div>
		<div class="Hui-tabNav-more btn-group"><a id="js-tabNav-prev" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d4;</i></a><a id="js-tabNav-next" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d7;</i></a></div>
</div>
	<div id="iframe_box" class="Hui-article">
		<div class="show_iframe">
			<div style="display:none" class="loading"></div>
			<iframe scrolling="yes" frameborder="0" src="Welcome"></iframe>
	</div>
</div>
</section>

<div class="contextMenu" id="Huiadminmenu">
	<ul>
		<li id="closethis">关闭当前 </li>
		<li id="closeall">关闭全部 </li>
</ul>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="~/Content/lib/jquery/1.9.1/jquery.min.js"></script> 
<script type="text/javascript" src="~/Content/lib/layer/2.4/layer.js"></script>
<script type="text/javascript" src="~/Content/static/h-ui/js/H-ui.min.js"></script>
<script type="text/javascript" src="~/Content/static/h-ui.admin/js/H-ui.admin.js"></script> 
    <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="lib/jquery.contextmenu/jquery.contextmenu.r2.js"></script>
<script type="text/javascript">
    $(function () {
        
    });

    /*个人信息*/
    function myselfinfo() {
        layer.open({
            type: 1,
            area: ['300px', '200px'],
            fix: false, //不固定
            maxmin: true,
            shade: 0.4,
            title: '查看信息',
            content: '<div>管理员信息</div>'
        });
    }

    /*资讯-添加*/
    function article_add(title, url) {
        var index = layer.open({
            type: 2,
            title: title,
            content: url
        });
        layer.full(index);
    }
    /*图片-添加*/
    function picture_add(title, url) {
        var index = layer.open({
            type: 2,
            title: title,
            content: url
        });
        layer.full(index);
    }
    /*产品-添加*/
    function product_add(title, url) {
        var index = layer.open({
            type: 2,
            title: title,
            content: url
        });
        layer.full(index);
    }
    /*用户-添加*/
    function member_add(title, url, w, h) {
        layer_show(title, url, w, h);
    }


</script> 


</body>
</html>